- name: To check value is greter than or not 
  hosts: local
  connection: local
  vars:
    n1: 23
  tasks:
  - name: print if number greter than 10
    ansible.builtin.debug:
      msg: "the given number {{ n1 }} is greter than 10"
    when: my_number > 10

  tasks:
  - name: print if number not  lessthan or equal  10
    ansible.builtin.debug:
      msg: "the given number {{ n1 }} is lessthan or equal to 10"
    when: my_number <= 10



