- name: create ec2 instances and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-037c4d2ca1f0da180
    sg_id: sg-0e93c1ca7a85c0236
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    instances:
    - mysql
    - app-server
    - web-server
  tasks:
  - name: install python libraries boto3 and botocore
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info

  - name: print ec2info
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"