- name: playbook to test datatypes
  hosts: local
  connections: local 
  vars:
    course_name: "Devops with AWS"
    duration: 120 
    topics:
    - linux
    - aws
    - ansible
    - shell
    live: true
    tools:
      ci: jemkins
      cloud: aws
      containarization: kubernetes
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello i joined {{ course_name }},the course duration is {{ duration }},topics are {{ topics }},is it {{ live }},tools cocered are {{ tools }}"