- name: play1
  hosts: web
  connection: local
  tasks:
  - name: play1 and task1
    ansible.builtin.debug:
    msg: "Hello from play1 and task1"

- name: play2
  hosts: web
  connection: local
  tasks:
  - name: play2 and task2
    ansible.builtin.debug:
    msg: "Hello from play2 and task2"

- name: play3
  hosts: web
  connection: local
  tasks:
  - name: play3 and task3
    ansible.builtin.debug:
    msg: "Hello from play3 and task3"