- name: nginx installation 
  hosts: web
  tasks:
  - name: nginx installation
    ansible.builtin.package:
      name: nginx
      state: installed
  - name: nginx start 
    ansible.builtin.service:
      name: nginx
      state: started


