- name: install nginx
  hosts: web
  become: yes
  tasks:
    - name: install niginx
      ansible.builtin.package:
       name: nginx
       state: installed
    - name: start nginx
      ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes
    - name: Print all gathered facts
      ansible.builtin.debug:
        var: ansible_facts  