- name: promts
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: please enter course name
    private: false
  - name: DURATION
    prompt: please enter duration
    private: false
  - name: TRAINER
    prompt: please enter trainer name
    private: false 
  tasks:
  - name: print1
    ansible.builtin.debug:
      msg: "course is  {{ COURSE }} and duration is {{ DURATION }} and trainer is {{ TRAINER }}"
