- name: to register output
  hosts: web 
  tasks:
  - name: to list ls command
    ansible.builtin.command: ls -ltr
    register: output

  - name: to register ls command output
    ansible.builtin.debug:
      msg: "ls command result is {{ output }}"