- name: variable
  hosts: web
  vars:
   person: kamal
  tasks:
  - name: to print variables
    vars:
      person1: kamalreddy
    ansible.builtin.debug:
      msg: "hello {{ person1 }}"
  - name: to print list of fruits
    vars:
      fruits: "apple,banana,mango"
    ansible.builtin.debug:
      # msg: "fruits are {{ fruits | split(',') }}"
      msg: "fruits are {{ fruits }}"

  - name: to convert map into list
    vars:
      cource:
        name: "devops with aws"
        duration: 10hrs
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "cource is {{ cource | dict2items }}"

  - name: to convert list into map
    vars:
      cource:
      - {'key': 'name', 'value': 'devops with aws'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'duration', 'value': '10hrs'}
    ansible.builtin.debug:
      msg: "cource is {{ cource | items2dict }}"

  - name: to convert into lower
    vars:
      name: "K KAMAlakarREDDY"
    ansible.builtin.debug:
      msg: "name is {{ name | lower }}"

  - name: to convert lower into upper
    vars:
      name: "k kamalakaRrEdDy"
    ansible.builtin.debug:
      msg: "name is {{ name | upper }}"