- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with AWS"
    DURATION: "120 HOURS"
    TRAINER: "SIVAKUMAR"
  tasks:
  - name: print
    vars:
      COURSE: ansible
    ansible.builtin.debug:
      msg: "course is {{ COURSE }} and duration is {{ DURATION }} and trainer is {{ TRAINER }}"


  - name: print1
    vars:
      COURSE: ansible
    ansible.builtin.debug:
      msg: "course is  {{ COURSE }} and duration is {{ DURATION }} and trainer is {{ TRAINER }}"